events { worker_connections 1024; }

http {
  upstream user_service    { server user-service:3001; }
  upstream product_service { server product-service:3002; }
  upstream order_service   { server order-service:3003; }

  server {
    listen 80;
    server_name _;

    location /api/auth     { proxy_pass http://user_service;    }
    location /api/users    { proxy_pass http://user_service;    }
    location /api/products { proxy_pass http://product_service; }
    location /api/orders   { proxy_pass http://order_service;   }

    location /health {
      default_type application/json;
      return 200 '{"status":"ok","service":"api-gateway"}';
    }
  }
}
